//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnFieldStorageManagmentApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.21.104")]
        public string FieldIpAddress {
            get {
                return ((string)(this["FieldIpAddress"]));
            }
            set {
                this["FieldIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldComputerUserName {
            get {
                return ((string)(this["FieldComputerUserName"]));
            }
            set {
                this["FieldComputerUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldComputerPassword {
            get {
                return ((string)(this["FieldComputerPassword"]));
            }
            set {
                this["FieldComputerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StorageServerUserName {
            get {
                return ((string)(this["StorageServerUserName"]));
            }
            set {
                this["StorageServerUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StorageServerPassword {
            get {
                return ((string)(this["StorageServerPassword"]));
            }
            set {
                this["StorageServerPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\goji\\ToSend")]
        public string FieldDirectoryToMinotor {
            get {
                return ((string)(this["FieldDirectoryToMinotor"]));
            }
            set {
                this["FieldDirectoryToMinotor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("r:\\")]
        public string StorageDirectoryToUpload {
            get {
                return ((string)(this["StorageDirectoryToUpload"]));
            }
            set {
                this["StorageDirectoryToUpload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UploadMode {
            get {
                return ((int)(this["UploadMode"]));
            }
            set {
                this["UploadMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteAllUploadedFilesEvery {
            get {
                return ((bool)(this["DeleteAllUploadedFilesEvery"]));
            }
            set {
                this["DeleteAllUploadedFilesEvery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12:00:00")]
        public string DeleteAllUploadedFilesTimer {
            get {
                return ((string)(this["DeleteAllUploadedFilesTimer"]));
            }
            set {
                this["DeleteAllUploadedFilesTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartWatchWrongFiles {
            get {
                return ((bool)(this["StartWatchWrongFiles"]));
            }
            set {
                this["StartWatchWrongFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string uploadWrongFilesDirectory {
            get {
                return ((string)(this["uploadWrongFilesDirectory"]));
            }
            set {
                this["uploadWrongFilesDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SyncDirectory {
            get {
                return ((string)(this["SyncDirectory"]));
            }
            set {
                this["SyncDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecoursiveSync {
            get {
                return ((bool)(this["RecoursiveSync"]));
            }
            set {
                this["RecoursiveSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shamay")]
        public string OperatorUserName {
            get {
                return ((string)(this["OperatorUserName"]));
            }
            set {
                this["OperatorUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OperationsByUser {
            get {
                return ((bool)(this["OperationsByUser"]));
            }
            set {
                this["OperationsByUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WatsonRunning {
            get {
                return ((bool)(this["WatsonRunning"]));
            }
            set {
                this["WatsonRunning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddDateToUploadDir {
            get {
                return ((bool)(this["AddDateToUploadDir"]));
            }
            set {
                this["AddDateToUploadDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0:0:1")]
        public string TriggeTime {
            get {
                return ((string)(this["TriggeTime"]));
            }
            set {
                this["TriggeTime"] = value;
            }
        }
    }
}
